[build]
  functions = "functions"
  publish = "public"

[functions.app]
  external_node_modules = ["express", "ejs", "serve-favicon"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/(.*)"
  status = 200
  to = "/.netlify/functions/app/:splat"